# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\rafae\OneDrive\Escritorio\Proyecto_Calibration_termopar\views\View_Curva_ajuste\view_curva_ajuste.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1917, 1041)
        Dialog.setStyleSheet("QDialog {\n"
"    background-color: white;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: #ccc;\n"
"    border-radius: 5px;\n"
"    box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.3);\n"
"}")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(580, 60, 1321, 961))
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: white;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: #ccc;\n"
"    border-radius: 5px;\n"
"    box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.3);\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(30, 40, 611, 421))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 571, 391))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.grafica_layout1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.grafica_layout1.setContentsMargins(0, 0, 0, 0)
        self.grafica_layout1.setObjectName("grafica_layout1")
        self.lbl_constantea_grafica1 = QtWidgets.QLabel(self.frame_2)
        self.lbl_constantea_grafica1.setGeometry(QtCore.QRect(20, 10, 121, 16))
        self.lbl_constantea_grafica1.setObjectName("lbl_constantea_grafica1")
        self.lbl_constanteb_grafica1 = QtWidgets.QLabel(self.frame_2)
        self.lbl_constanteb_grafica1.setGeometry(QtCore.QRect(20, 30, 121, 16))
        self.lbl_constanteb_grafica1.setObjectName("lbl_constanteb_grafica1")
        self.lbl_ecuacion_grafica1 = QtWidgets.QLabel(self.frame_2)
        self.lbl_ecuacion_grafica1.setGeometry(QtCore.QRect(400, 10, 191, 16))
        self.lbl_ecuacion_grafica1.setText("")
        self.lbl_ecuacion_grafica1.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_ecuacion_grafica1.setObjectName("lbl_ecuacion_grafica1")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(30, 490, 611, 421))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame_3)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 10, 571, 401))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.grafica_layout3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.grafica_layout3.setContentsMargins(0, 0, 0, 0)
        self.grafica_layout3.setObjectName("grafica_layout3")
        self.lbl_constantea_grafica3 = QtWidgets.QLabel(self.frame_3)
        self.lbl_constantea_grafica3.setGeometry(QtCore.QRect(20, 10, 121, 16))
        self.lbl_constantea_grafica3.setObjectName("lbl_constantea_grafica3")
        self.lbl_constanteb_grafica3 = QtWidgets.QLabel(self.frame_3)
        self.lbl_constanteb_grafica3.setGeometry(QtCore.QRect(20, 30, 121, 16))
        self.lbl_constanteb_grafica3.setObjectName("lbl_constanteb_grafica3")
        self.lbl_ecuacion_grafica3 = QtWidgets.QLabel(self.frame_3)
        self.lbl_ecuacion_grafica3.setGeometry(QtCore.QRect(400, 10, 191, 16))
        self.lbl_ecuacion_grafica3.setText("")
        self.lbl_ecuacion_grafica3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_ecuacion_grafica3.setObjectName("lbl_ecuacion_grafica3")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(680, 40, 611, 421))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.frame_4)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 10, 571, 391))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.grafica_layout2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.grafica_layout2.setContentsMargins(0, 0, 0, 0)
        self.grafica_layout2.setObjectName("grafica_layout2")
        self.lbl_constanteb_grafica2 = QtWidgets.QLabel(self.frame_4)
        self.lbl_constanteb_grafica2.setGeometry(QtCore.QRect(20, 30, 121, 16))
        self.lbl_constanteb_grafica2.setObjectName("lbl_constanteb_grafica2")
        self.lbl_constantea_grafica2 = QtWidgets.QLabel(self.frame_4)
        self.lbl_constantea_grafica2.setGeometry(QtCore.QRect(20, 10, 121, 16))
        self.lbl_constantea_grafica2.setObjectName("lbl_constantea_grafica2")
        self.lbl_ecuacion_grafica2 = QtWidgets.QLabel(self.frame_4)
        self.lbl_ecuacion_grafica2.setGeometry(QtCore.QRect(400, 10, 191, 16))
        self.lbl_ecuacion_grafica2.setText("")
        self.lbl_ecuacion_grafica2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_ecuacion_grafica2.setObjectName("lbl_ecuacion_grafica2")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setGeometry(QtCore.QRect(680, 490, 611, 421))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.frame_5)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(20, 10, 571, 401))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.grafica_layout4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.grafica_layout4.setContentsMargins(0, 0, 0, 0)
        self.grafica_layout4.setObjectName("grafica_layout4")
        self.lbl_constantea_grafica4 = QtWidgets.QLabel(self.frame_5)
        self.lbl_constantea_grafica4.setGeometry(QtCore.QRect(20, 10, 121, 16))
        self.lbl_constantea_grafica4.setObjectName("lbl_constantea_grafica4")
        self.lbl_constanteb_grafica4 = QtWidgets.QLabel(self.frame_5)
        self.lbl_constanteb_grafica4.setGeometry(QtCore.QRect(20, 30, 121, 16))
        self.lbl_constanteb_grafica4.setObjectName("lbl_constanteb_grafica4")
        self.lbl_ecuacion_grafica4 = QtWidgets.QLabel(self.frame_5)
        self.lbl_ecuacion_grafica4.setGeometry(QtCore.QRect(400, 10, 191, 16))
        self.lbl_ecuacion_grafica4.setText("")
        self.lbl_ecuacion_grafica4.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_ecuacion_grafica4.setObjectName("lbl_ecuacion_grafica4")
        self.btn_exportar_datos = QtWidgets.QPushButton(self.frame)
        self.btn_exportar_datos.setGeometry(QtCore.QRect(600, 920, 121, 31))
        self.btn_exportar_datos.setStyleSheet("QPushButton {\n"
"    background-color: #4c8bf5;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 5px 15px;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3a71d6;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2b569c;\n"
"}\n"
"")
        self.btn_exportar_datos.setObjectName("btn_exportar_datos")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(580, 10, 161, 21))
        self.label_10.setStyleSheet("QLabel {\n"
"    color: #333;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    border-color: transparent\n"
"}\n"
"\n"
"")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.frame_6 = QtWidgets.QFrame(Dialog)
        self.frame_6.setGeometry(QtCore.QRect(20, 60, 541, 961))
        self.frame_6.setStyleSheet("QFrame {\n"
"    background-color: white;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: #ccc;\n"
"    border-radius: 5px;\n"
"    box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.3);\n"
"}\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label = QtWidgets.QLabel(self.frame_6)
        self.label.setGeometry(QtCore.QRect(150, 10, 241, 21))
        self.label.setStyleSheet("QLabel {\n"
"    color: #333;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    border-color: transparent\n"
"}\n"
"\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.tableview_promedios = QtWidgets.QTableView(self.frame_6)
        self.tableview_promedios.setGeometry(QtCore.QRect(20, 40, 501, 901))
        self.tableview_promedios.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableview_promedios.setObjectName("tableview_promedios")
        self.frame_7 = QtWidgets.QFrame(Dialog)
        self.frame_7.setGeometry(QtCore.QRect(-10, 0, 1961, 41))
        self.frame_7.setStyleSheet("QFrame {\n"
"    background-color: #97775b;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: #ccc;\n"
"    border-radius: 5px;\n"
"    box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.3);\n"
"}\n"
"")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.btn_regresar = QtWidgets.QPushButton(self.frame_7)
        self.btn_regresar.setGeometry(QtCore.QRect(1820, -10, 93, 61))
        self.btn_regresar.setStyleSheet("background-color: transparent\n"
"")
        self.btn_regresar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/images/iconos/regresar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_regresar.setIcon(icon)
        self.btn_regresar.setIconSize(QtCore.QSize(35, 35))
        self.btn_regresar.setCheckable(False)
        self.btn_regresar.setAutoRepeat(False)
        self.btn_regresar.setObjectName("btn_regresar")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lbl_constantea_grafica1.setText(_translate("Dialog", "a ="))
        self.lbl_constanteb_grafica1.setText(_translate("Dialog", "b ="))
        self.lbl_constantea_grafica3.setText(_translate("Dialog", "a ="))
        self.lbl_constanteb_grafica3.setText(_translate("Dialog", "b ="))
        self.lbl_constanteb_grafica2.setText(_translate("Dialog", "b ="))
        self.lbl_constantea_grafica2.setText(_translate("Dialog", "a ="))
        self.lbl_constantea_grafica4.setText(_translate("Dialog", "a ="))
        self.lbl_constanteb_grafica4.setText(_translate("Dialog", "b ="))
        self.btn_exportar_datos.setText(_translate("Dialog", "Exportar"))
        self.label_10.setText(_translate("Dialog", "Curva de ajuste"))
        self.label.setText(_translate("Dialog", "Tabla de promedios"))
