# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\rafae\OneDrive\Escritorio\Proyecto_Calibration_termopar\views\View_Arduino_setting\view_ardiono_setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(263, 476)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(10, 9, 241, 451))
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: white;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: #ccc;\n"
"    border-radius: 5px;\n"
"    box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.3);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.cmb_puertosA = QtWidgets.QComboBox(self.frame)
        self.cmb_puertosA.setGeometry(QtCore.QRect(20, 80, 201, 22))
        self.cmb_puertosA.setObjectName("cmb_puertosA")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 60, 91, 16))
        self.label.setStyleSheet("border-color: none")
        self.label.setObjectName("label")
        self.btn_aceptar = QtWidgets.QPushButton(self.frame)
        self.btn_aceptar.setGeometry(QtCore.QRect(20, 410, 93, 28))
        self.btn_aceptar.setStyleSheet("background-color: rgb(45,215, 89);\n"
"color: rgb(255, 255, 255);")
        self.btn_aceptar.setObjectName("btn_aceptar")
        self.btn_cancelar = QtWidgets.QPushButton(self.frame)
        self.btn_cancelar.setGeometry(QtCore.QRect(130, 410, 93, 28))
        self.btn_cancelar.setStyleSheet("background-color: rgb(255,90, 108);\n"
"color: rgb(255, 255, 255);")
        self.btn_cancelar.setObjectName("btn_cancelar")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border-color: none")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.lbl_msj = QtWidgets.QLabel(self.frame)
        self.lbl_msj.setGeometry(QtCore.QRect(24, 150, 191, 131))
        self.lbl_msj.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_msj.setObjectName("lbl_msj")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Puerto Arduino"))
        self.btn_aceptar.setText(_translate("Dialog", "Aceptar"))
        self.btn_cancelar.setText(_translate("Dialog", "Cancelar"))
        self.label_2.setText(_translate("Dialog", "Configuración de Arduino"))
        self.lbl_msj.setText(_translate("Dialog", "..."))
